DROP TABLE IF EXISTS parser;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS card;
DROP TABLE IF EXISTS note_link;
DROP TABLE IF EXISTS note_tag;
DROP TABLE IF EXISTS card_tag;
DROP TABLE IF EXISTS review_log;
