[package]
name = "spares_core"
description = "A spaced repetition system written in Rust"
version = "0.0.1-alpha.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
async-trait = "0.1.89"
blake3 = "1.8.4"
chrono = { version = "0.4.44", features = ["serde"] }
etcetera = "0.11.0"
fancy-regex = "0.17.0"
# fsrs = { git = "https://github.com/open-spaced-repetition/rs-fsrs" }
rs-fsrs = { version = "1.2.1" }
futures = "0.3.32"
indexmap = "2.13.0"
indicatif = { version = "0.18.4", features = ["rayon"] }
indoc = "2.0.7"
inquire = "0.9.4"
itertools = "0.14.0"
log = "0.4.29"
miette = { version = "7.6.0" }
rand = "0.10.0"
rayon = "1.11.0"
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
serde_with = { version = "3.18.0", features = ["chrono_0_4"] }
shellexpand = "3.1.2"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "chrono", "json", "migrate", "regexp"] }
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
thiserror = "2.0.18"
toml_edit = { version = "0.25.5", features = ["serde"] }
trash = "5.2.5"
typst-syntax = "0.14.2"
xmltree = { version = "0.12.0", features = ["attribute-order"] }
unscanny = "0.1.0"
image = "0.25.10"
resvg = "0.47.0"
tiny-skia = "0.12.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
uuid = { version = "1.22.0", features = [
    "serde",
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]}

# [features]
# testing = [] # Used to mitigate effects to local data files in integration testing. See <https://www.reddit.com/r/rust/comments/ny6k3f/cfgtest_doesnt_take_affect_when_running/>.

[lints]
workspace = true
