[package]
name = "spares_cli"
version = "0.0.1-alpha.1"
description = "A CLI to interface with spares"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "spares"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
clap = { version = "4.6.0", features = ["derive", "cargo", "env"] }
clap_complete_command = "0.6.1"
colored = "3.1.1"
copy_dir = "0.1.3"
env_logger = "0.11.9"
indexmap = "2.13.0"
indicatif = { version = "0.18.4", features = ["rayon"] }
inquire = { version = "0.9.4", features = ["date"] }
itertools = "0.14.0"
log = "0.4.29"
miette = { version = "7.6.0", features = ["fancy"] }
open = "5.3.3"
petgraph = "0.8.3"
rayon = "1.11.0"
reqwest = { version = "0.13.2", features = ["json", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
sha256 = "1.6.0"
serde_json = { version = "1.0.149", features = ["preserve_order"] }
spares_core = { path = "../spares_core" }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "chrono", "json", "migrate", "regexp"] }
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
tokio = { version = "1.50.0", features = ["full"] }
walkdir = "2.5.0"

[lints]
workspace = true
