[package]
name = "spares_frontend"
version = "0.0.1-alpha.1"
description = "A utility to launch the spares frontend"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }

[lints]
workspace = true
